apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: rafflethor
spec:
  selector:
    matchLabels:
      app: rafflethor
      tier: web
  replicas: 1
  template:
    metadata:
      labels:
        app: rafflethor
        tier: web
    spec:
      containers:
      - image: rafflethor-docker-rafflethor.bintray.io/web:1.0.0
        name: web
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: rafflethor
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: rafflethor
    tier: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: rafflethor
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: web.services.rafflethor.io
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
